project:
  type: website
  output-dir: docs

website:
  title: "Eugene Sogbe"

  navbar:
    left:
      - href: index.qmd
        text: Home

      - href: profile.qmd
        text: Profile

      
      - href: publications.qmd
        text: Publications

      - href: projects.qmd
        text: Projects

      - href: teaching.qmd
        text: Teaching

      - href: opportunities.qmd
        text: Opportunities

      - href: resources.qmd
        text: Resources

      - href: cv.qmd
        text: Curriculum Vitae

      - href: contact.qmd
        text: Contact

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    title-block: false